# templates_list.py

madlib_templates = [
    "Once upon a time in {place}, there was a {adjective} {noun} who loved to {verb}.",
    "In the middle of {place}, a {adjective} {noun} decided to {verb} all day long.",
    "A {adjective} {noun} traveled to {place} just to {verb}.",
    "Legends say in {place}, the {adjective} {noun} will {verb} forever.",
    "Every morning, the {adjective} {noun} from {place} wakes up ready to {verb}.",
    "Nobody expected the {adjective} {noun} in {place} to suddenly {verb}.",
    "In {place}, the {adjective} {noun} found a way to {verb} better than anyone.",
    "That {adjective} {noun} in {place} refused to stop {verb}ing.",
    "Strangely enough, a {adjective} {noun} was spotted trying to {verb} in {place}.",
    "The world remembers when the {adjective} {noun} of {place} decided to {verb}.",
    "During the festival in {place}, the {adjective} {noun} couldn’t resist to {verb}.",
    "The {adjective} {noun} from {place} became famous for trying to {verb}.",
    "Long ago, a {adjective} {noun} dreamed to {verb} in {place}.",
    "Suddenly, the {adjective} {noun} appeared in {place} just to {verb}.",
    "Even in {place}, people say the {adjective} {noun} loved to {verb}.",
    "Hidden in {place}, the {adjective} {noun} plotted to {verb}.",
    "Unexpectedly, a {adjective} {noun} was born in {place} and started to {verb}.",
    "The {adjective} {noun} of {place} always teaches others how to {verb}.",
    "After years in {place}, the {adjective} {noun} finally learned to {verb}.",
    "Whenever in {place}, people know the {adjective} {noun} is about to {verb}.",
    "A {adjective} {noun} once dared to {verb} inside {place}.",
    "They still tell stories in {place} about a {adjective} {noun} who tried to {verb}.",
    "In {place}, a {adjective} {noun} became a legend by {verb}ing.",
    "Everyone laughed when the {adjective} {noun} in {place} started to {verb}.",
    "Once, a {adjective} {noun} challenged the king of {place} to {verb}.",
    "Even the skies above {place} echo when the {adjective} {noun} {verb}s.",
    "The {adjective} {noun} traveled far to reach {place} and finally {verb}.",
    "A secret tale of {place} tells of a {adjective} {noun} who loved to {verb}.",
    "In {place}, no one forgets how the {adjective} {noun} tried to {verb}.",
    "Long before now, a {adjective} {noun} was destined to {verb} in {place}.",
    "To this day, {place} honors the {adjective} {noun} who could {verb}.",
    "The {adjective} {noun} always believed that {place} was made to {verb}.",
    "When the {adjective} {noun} entered {place}, they started to {verb}.",
    "Every traveler in {place} whispers about the {adjective} {noun} who {verb}s.",
    "No one dared to stop the {adjective} {noun} in {place} from {verb}ing.",
    "Suddenly in {place}, the {adjective} {noun} began to {verb} non-stop.",
    "Every child in {place} dreams of being a {adjective} {noun} who can {verb}.",
    "The history of {place} includes a {adjective} {noun} who once {verb}ed.",
    "In the heart of {place}, a {adjective} {noun} danced while {verb}ing.",
    "The {adjective} {noun} knew that {place} was the only place to {verb}.",
    "Deep inside {place}, the {adjective} {noun} trained to {verb}.",
    "When storms hit {place}, the {adjective} {noun} continued to {verb}.",
    "The legend of the {adjective} {noun} from {place} who {verb}ed is told often.",
    "Even today, {place} remembers the {adjective} {noun} who {verb}ed.",
    "From {place}, a {adjective} {noun} spread joy by {verb}ing.",
    "Every hero in {place} was inspired by the {adjective} {noun} who {verb}ed.",
    "Sometimes the {adjective} {noun} in {place} just wanted to {verb}.",
    "A {adjective} {noun} once shocked {place} by {verb}ing out loud.",
    "Throughout {place}, the {adjective} {noun} is admired for {verb}ing.",
    "Back in ancient {place}, a {adjective} {noun} once tried to {verb}.",
    "The {adjective} {noun} discovered that {place} was built to {verb}.",
    "Whenever trouble hit {place}, the {adjective} {noun} would {verb}.",
    "In {place}, every story starts with a {adjective} {noun} trying to {verb}.",
    "That {adjective} {noun} in {place} was remembered because it loved to {verb}.",
    "Even animals in {place} knew the {adjective} {noun} could {verb}.",
    "Once a {adjective} {noun} stood tall in {place} and began to {verb}.",
    "The {adjective} {noun} who {verb}ed in {place} became a myth.",
    "Every book in {place} tells of a {adjective} {noun} who {verb}ed.",
    "All across {place}, cheers were heard as the {adjective} {noun} {verb}ed.",
    "From the top of {place}, the {adjective} {noun} shouted while {verb}ing.",
    "No story of {place} is complete without a {adjective} {noun} who {verb}ed.",
    "Even when the sun set in {place}, the {adjective} {noun} continued to {verb}.",
    "The {adjective} {noun} from {place} would never stop {verb}ing.",
    "Generations in {place} will remember the {adjective} {noun} that {verb}ed.",
    "Every festival in {place} honors the {adjective} {noun} who {verb}ed.",
    "Legends grew in {place} about a {adjective} {noun} who {verb}ed for fun.",
    "A {adjective} {noun} journeyed into {place} just to {verb}.",
    "Inside {place}, the {adjective} {noun} carved its destiny by {verb}ing.",
    "Many tales in {place} speak of the {adjective} {noun} who {verb}ed.",
    "Even strangers in {place} knew the {adjective} {noun} was born to {verb}.",
    "The {adjective} {noun} once sang in {place} while {verb}ing.",
    "It is said the {adjective} {noun} from {place} can {verb} better than anyone.",
    "During the night in {place}, the {adjective} {noun} secretly {verb}ed.",
    "At sunrise in {place}, the {adjective} {noun} prepared to {verb}.",
    "That {adjective} {noun} will forever be remembered in {place} for {verb}ing.",
    "Even far away, people hear of the {adjective} {noun} in {place} who {verb}ed.",
    "In the archives of {place}, the {adjective} {noun} who {verb}ed is written.",
    "The {adjective} {noun} wanted nothing more than to {verb} in {place}.",
    "Hidden deep in {place}, the {adjective} {noun} mastered {verb}ing.",
    "Every visitor in {place} knows the {adjective} {noun} might {verb}.",
    "The {adjective} {noun} shocked {place} by daring to {verb}.",
    "Children in {place} often dream of being a {adjective} {noun} that {verb}s.",
    "One {adjective} {noun} turned {place} upside down by {verb}ing.",
    "The most {adjective} {noun} was found {verb}ing in {place}.",
    "In {place}, history changed when a {adjective} {noun} decided to {verb}.",
    "A wandering {adjective} {noun} walked into {place} and started {verb}ing.",
    "At the gates of {place}, the {adjective} {noun} prepared to {verb}.",
    "Songs in {place} tell of the {adjective} {noun} who {verb}ed long ago.",
    "The story of {place} begins with a {adjective} {noun} who {verb}ed.",
    "Throughout history, {place} praised the {adjective} {noun} who {verb}ed.",
    "That {adjective} {noun} in {place} will inspire others to {verb}.",
    "Finally, the {adjective} {noun} found peace in {place} by {verb}ing.",
    "The {adjective} {noun} chose {place} as the perfect spot to {verb}.",
    "Today in {place}, the {adjective} {noun} still tries to {verb}.",
    "No one in {place} could believe how much the {adjective} {noun} loved to {verb}.",
    "A strange {adjective} {noun} appeared in {place} just to {verb}.",
    "Even the walls of {place} echo when the {adjective} {noun} {verb}s.",
]
